import { z } from "zod";

export const photoStatusSchema = z.enum(["draft", "saved"]);
export const mediaTypeSchema = z.enum(["photo", "video"]);
export const photoStylePresetSchema = z.enum([
  "original",
  "classic",
  "noir",
  "warm",
  "cool",
  "pop",
]);
export const photoLayoutSchema = z.enum(["single", "strip"]);
export const cameraFilterPresetSchema = z.enum([
  "natural",
  "golden-hour",
  "glam",
  "cyber-pop",
  "vhs-night",
  "soft-blur",
  "sepia",
  "vintage",
  "bw",
  "70s",
  "80s",
  "polaroid",
  "cool",
  "warm",
  "dramatic",
  "dreamy",
  "fade",
  "matte",
  "vivid",
  "muted",
  "cinema",
  "sunset",
  "ocean",
  "forest",
  "noir",
  "grain",
  "clarendon",
  "gingham",
  "moon",
  "lark",
  "reyes",
  "juniper",
  "valencia",
  "xpro",
  "sierra",
  "willow",
  "lofi",
  "inkwell",
  "nashville",
  "stinson",
  "vesper",
  "earlybird",
  "brannan",
  "sutro",
  "toaster",
  "walden",
  "hefe",
  "mayfair",
  "hudson",
]);

export const cameraEffectPresetSchema = z.enum([
  "none",
  "vignette",
  "light-leak",
  "film-grain",
  "bokeh",
  "scratch",
  "scanlines",
  "color-splash",
  "warm-glow",
  "cool-glow",
  "retro-border",
  "double-exposure",
  "rain",
  "snow",
  "sun-flare",
  "ghost",
  "glitch",
  "chromatic",
  "film-burn",
  "lens-flare",
  "dust",
  "split-tone",
  "neon-glow",
  "retro-film",
  "prism",
  "halftone",
  "noise",
  "film-noir",
  "vintage-teal",
  "disco",
  "sparkle",
  "heart-frame",
  "star-burst",
  "confetti",
  "butterfly",
  "crown",
  "fire",
  "ice",
  "rainbow-border",
  "leaves",
  "bubbles",
  "cat-ears",
  "devil-horns",
  "angel-halo",
  "glasses",
  "mustache",
  "blush",
  "tears",
  "sweat",
  "angry",
  "surprised",
]);

export const editorSettingsSchema = z.object({
  preset: photoStylePresetSchema,
  brightness: z.number().min(50).max(150),
  contrast: z.number().min(50).max(150),
  saturation: z.number().min(0).max(200),
  vignette: z.number().min(0).max(100),
});

export const photoRecordSchema = z.object({
  id: z.string().min(1),
  sessionId: z.string().min(1),
  mediaType: mediaTypeSchema,
  status: photoStatusSchema,
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  sourceImage: z.string().min(1),
  renderedImage: z.string().min(1),
  sourceVideo: z.string().min(1).optional(),
  renderedVideo: z.string().min(1).optional(),
  durationMs: z.number().min(0).optional(),
  cameraFilter: cameraFilterPresetSchema.optional(),
  settings: editorSettingsSchema,
  layout: photoLayoutSchema,
  name: z.string().min(1).optional(),
});

export const sessionGallerySchema = z.object({
  version: z.literal(2),
  sessionId: z.string().min(1),
  photos: z.array(photoRecordSchema),
});

export type EditorSettingsDto = z.infer<typeof editorSettingsSchema>;
export type PhotoRecordDto = z.infer<typeof photoRecordSchema>;
export type SessionGalleryDto = z.infer<typeof sessionGallerySchema>;
